hydra:
  run:
    dir: ./evaluations/predictions/bbox/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

weights: runs/traffic_light_2020_undistorted/yolov5x6_1280_cross_prod_visible_only/weights/best.pt 
dst: predictions.json
data:
  path: ~/dataset/traffic_lights_entron_classification_v2/focal_len=650__sensor_size_hw=1200x1920/
  image_size: [1600, 960]
  image_crop: [0, 0, 1920, 1152]
  batch_size: 22
  num_workers: 0
devices: 0
